### ISSUE TITLE
labels with local state

### ISSUE THREAD

**Issue by Sorseg** [PoOnesNerfect/bevy_bsml#6]
I am trying to use `bevy_bsml` with [render_ui_to_texture](https://github.com/bevyengine/bevy/blob/v0.14.1/examples/ui/render_ui_to_texture.rs) example.
For it to work, the node needs a `TargetCamera(texture_camera)` component, having an entity id in it, which does not work with `bevy_bsml=0.14.8`,
the error says 
```rust
error[E0434]: can't capture dynamic environment in a fn item
  --> src/main.rs:65:101
   |
65 |     (node class=[W_FULL, H_FULL, JUSTIFY_CENTER, ITEMS_CENTER, BG_TRANSPARENT] labels=[TargetCamera(texture_camera)]) {
   |                                                                                                     ^^^^^^^^^^^^^^
   |
   = help: use the `|| { ... }` closure form instead
```

**Comment by Sorseg** [comment]
I realized the macro returns the `EntityCommands`, so I just add `.insert(TargetCamera(texture_camera));` to the end
